#!/bin/sh
. $(dirname $0)/_/husky.sh
set -e
npm run build
npm run test
difffiles=$(git diff --name-only --staged --diff-filter=d)
npm run lint
if [ -n "$difffiles" ]; then echo $difffiles | xargs git add; fi
git diff --exit-code package.json package-lock.json
npm version patch --git-tag-version false
git add package.json package-lock.json
