#!/bin/sh

. $(dirname $0)/_/husky.sh

set -e

modifiedfiles=$(git diff --name-only --staged --diff-filter=d)
difffiles=$(git diff --name-only --staged)

if [ -n "$difffiles" ]
then
    echo $modifiedfiles | xargs git diff --exit-code package.json package-lock.json
    npm run build
    npm run test
    npm run lint
    npm version patch --git-tag-version false
    echo $modifiedfiles | xargs git add package.json package-lock.json
fi
