#!/bin/sh
. $(dirname $0)/_/husky.sh
set -e
difffiles=$(git diff --name-only --staged --diff-filter=d)
if [ -n "$difffiles" ]; then
    npm run build
    npm run test
    npm run lint
    echo $difffiles | xargs git add
    git diff --exit-code package.json package-lock.json
    npm version patch --git-tag-version false
    git add package.json package-lock.json
fi
