on:
  push:
    branches:
      - main
jobs:
  publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      REPO_OWNER: ${{ github.event.repository.owner.name }}
      TARGET_BRANCH_NAME: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: branch-name
        uses: tj-actions/branch-names@v4.3
      - uses: actions/setup-node@v2
        with:
           registry-url: https://registry.npmjs.org/
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'true'
        run: |
          npm install
          npm publish
      - if: steps.check.outputs.changed == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.check.outputs.version }}
      - if: steps.check.outputs.changed == 'true'
        run: |
          npm run docs
          git config user.name $REPO_OWNER
          git add -f docs
          git commit --amend --allow-empty-message --no-verify -m '' --reset-author
          git push origin `git subtree split --prefix docs ${{ steps.branch-name.outputs.current_branch }}`:$TARGET_BRANCH_NAME --force ||  git subtree push --prefix docs origin $TARGET_BRANCH_NAME
